const fs = require('fs');
const file = 'c:\\Users\\Administrador\\Documents\\PaginaGimnasio\\PaginaGimnasio\\src\\App.jsx';
let text = fs.readFileSync(file, 'utf8');
const replacements = [
  ['Â·', '·'],
  ['â€“', '–'],
  ['â€”', '—'],
  ['Â½', '½'],
  ['Ã—', '×'],
  ['Â¡', '¡'],
  ['Â¿', '¿'],
  ['Ã¡', 'á'],
  ['Ã©', 'é'],
  ['Ã­', 'í'],
  ['Ã³', 'ó'],
  ['Ãº', 'ú'],
  ['Ã¼', 'ü'],
  ['Ã±', 'ñ'],
  ['Ã', 'Á'],
  ['Ã‰', 'É'],
  ['Ã', 'Í'],
  ['Ã“', 'Ó'],
  ['Ãš', 'Ú'],
  ['Ãœ', 'Ü'],
  ['Ã‘', 'Ñ'],
  ['AÃºn', 'Aún'],
  ['AÃ±adido', 'Añadido'],
  ['AÃ±ade', 'Añade'],
  ['AÃ±adir', 'Añadir'],
  ['AÃ±adidos', 'Añadidos'],
  ['aÃ±adidos', 'añadidos'],
  ['aÃ±adir', 'añadir'],
  ['librerÃ­a', 'librería'],
  ['librerÃ­a.', 'librería.'],
  ['sesiÃ³n', 'sesión'],
  ['progresiÃ³n', 'progresión'],
  ['visiÃ³n', 'visión'],
  ['mÃ©tricas', 'métricas'],
  ['MÃ©tricas', 'Métricas'],
  ['MÃ©trica', 'Métrica'],
  ['NavegaciÃ³n principal', 'Navegación principal'],
  ['GuÃ­a', 'Guía'],
  ['guÃ­a', 'guía'],
  ['Ãœltimo', 'Último'],
  ['Ãšltimo', 'Último'],
  ['Ãšltima', 'Última'],
  ['dÃ­as', 'días'],
  ['dÃ­a', 'día'],
  ['RÃ¡cha', 'Racha'],
  ['AÃºn no hay rutinas', 'Aún no hay rutinas'],
  ['AÃ±ade tus medidas', 'Añade tus medidas'],
  ['AÃ±ade tu primer peso', 'Añade tu primer peso'],
  ['AÃ±ade la configuraciÃ³n de Firebase para iniciar sesiÃ³n', 'Añade la configuración de Firebase para iniciar sesión'],
  ['MÃ©trica guardada localmente; no se pudo sincronizar', 'Métrica guardada localmente; no se pudo sincronizar'],
  ['MÃ©trica corporal aÃ±adida', 'Métrica corporal añadida'],
  ['AÃ±adir peso', 'Añadir peso'],
  ['AÃ±ade ejercicios desde la librerÃ­a para comenzar', 'Añade ejercicios desde la librería para comenzar'],
  ['Todos los dÃ­as', 'Todos los días'],
  ['Calentamiento Â· 5â€“10 min', 'Calentamiento · 5–10 min'],
  ['Ãšltima vez', 'Última vez'],
  ['Ãºltima', 'última'],
  ['ï»¿', ''],
  ['AÃºn', 'Aún'],
  ['Ã“', 'Ó'],
  ['Ã“N', 'ÓN'],
  ['PROGRESIÃ“N', 'PROGRESIÓN'],
  ['DATOS Y PROGRESIÃ“N', 'DATOS Y PROGRESIÓN'],
  ['Ãœltima', 'Última'],
  ['AÃ±ade', 'Añade'],
  ['AÃ±adido', 'Añadido'],
  ['MÃ©trico', 'Métrico'],
  ['CARGA REGISTRADA', 'CARGA REGISTRADA'],
  ['GrÃ¡fica de progresiÃ³n', 'Gráfica de progresión'],
  ['AÃ±adidos', 'Añadidos'],
  ['Ã–', 'Ö']
];
for (const [from, to] of replacements) {
  text = text.split(from).join(to);
}
fs.writeFileSync(file, text, 'utf8');
console.log('updated', 'bad chars?', /[ÃÂâ]/.test(text));
